version: '3.8'

services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    restart: unless-stopped
    ports:
      - "8081:8081"
#    environment:
#      SERVER_PORT: 1212

#    network_mode: host